### ISSUE TITLE
Abnormal results

### ISSUE THREAD

**Issue by ISOEhy** [TUW-VieVS/raPPPid#10]
I try this program with the smartphone data from google .However, the results are terrible. How to get a reasonable results. Can you share a setting file and paramter file?
![image](https://github.com/TUW-VieVS/raPPPid/assets/33491593/74c9a3c7-6f4e-4522-9bca-ce91594083df)
![image](https://github.com/TUW-VieVS/raPPPid/assets/33491593/3c6ccbb1-2b71-452f-bbf3-2c624e5f8927)

**Comment by ISOEhy** [comment]
the red line is results from rapppid

**Comment by mfglaner** [comment]
Please send me the RINEX file and settings from the GUI as a starting point.

**Comment by ISOEhy** [comment]
The obs file,results and setting files are followed.
[gnss_log - 1.zip](https://github.com/TUW-VieVS/raPPPid/files/13049480/gnss_log.-.1.zip)

**Comment by mfglaner** [comment]
The system noise on the coordinates should not be zero; this works only for a static receiver. Please use the following settings file as a starting point:
[settings_issuegithub.zip](https://github.com/TUW-VieVS/raPPPid/files/13052175/settings_issuegithub.zip)
However, these settings are only a rough idea and can definitely be tuned in several regards (e.g., system noise of the filter, thresholds of the measurement checks, and so on). Generally, kinematic smartphone data is a challenging topic. Furthermore, raPPPid is currently not tested and optimized with kinematic data (→future developments).
