### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by MoSaber88** [TUW-VieVS/raPPPid#13]
![410940449_1130250451746417_7234723832268059281_n](https://github.com/TUW-VieVS/raPPPid/assets/89976547/29598076-fb0e-43da-9496-61a19c24938c)
 
After loading the observation file, this error appears , how can I fix it ?

Thanks

**Comment by mfglaner** [comment]
Change the Matlab work folder to the WORK folder of raPPPid. The WORK folder of raPPPid is a subfolder of the program (/raPPPid/WORK/). Otherwise, relative paths are not working.
