### ISSUE TITLE
Error : Saving default parameters failed

### ISSUE THREAD

**Issue by MoSaber88** [TUW-VieVS/raPPPid#14]
![411186304_350259511116930_4170157833731040306_n](https://github.com/TUW-VieVS/raPPPid/assets/89976547/765d37e9-adad-43b5-a6ba-87b6117252a5)
![415629522_1040480353733969_8339710089536151800_n](https://github.com/TUW-VieVS/raPPPid/assets/89976547/0ebffc78-0560-4087-b1c2-27314a0136f3)

While open it gives me this error   ( Error : Saving default parameters failed )

how can I fix it ?

Thanks

**Comment by mfglaner** [comment]
Something went wrong when opening the GUI and saving the default parameters. I have no idea what the reason could be. However, you can safely ignore this error message because it does not affect the program.

**Comment by mfglaner** [comment]
Then there is another issue. This error is thrown when opening the GUI and does not affect the processing.
