### ISSUE TITLE
Multi freq. issue

### ISSUE THREAD

**Issue by MoSaber88** [TUW-VieVS/raPPPid#15]
how to enable receiver DCB estimation ?
![414192633_914803220178938_4092003782878751389_n](https://github.com/TUW-VieVS/raPPPid/assets/89976547/aa8f4a5c-7dfe-4dd8-a9de-5ca90d3a3f2d)

**Comment by mfglaner** [comment]
Go to "Estimation" on the menu bar, then:
→ Adjustment
→ Receiver DCBs
→ checkbox: Estimate
