### ISSUE TITLE
Multi freq. Issue

### ISSUE THREAD

**Issue by MoSaber88** [TUW-VieVS/raPPPid#16]
![413898025_3829533180651748_2370811778644370959_n](https://github.com/TUW-VieVS/raPPPid/assets/89976547/13ccc38b-d5c4-4aca-b09f-cca3150fd537)
this
![415872301_285524021197543_8867526101803911621_n](https://github.com/TUW-VieVS/raPPPid/assets/89976547/67b16c2b-81aa-4dfc-a109-251a51bbf7e5)
![413898025_3829533180651748_2370811778644370959_n](https://github.com/TUW-VieVS/raPPPid/assets/89976547/36796da9-888c-4dc7-83b9-ad824f219544)
 error happened while processing with multi freq option , but not happen with dual freq option

**Comment by mfglaner** [comment]
Please post the full error message. The first part is missing. 
Otherwise, I recommend to do a GPS only processing and add Galileo, GLONASS, and BeiDou one after each other.

**Comment by MoSaber88** [comment]
Here is the full error message :

Index exceeds the number of array elements (0).

Error in satelliteClock (line 77)
    idx = idx(1);                                   % preventing errors

Error in modelErrorSources (line 194)
    [dT_sat, noclock] = satelliteClock(sv, Ttr, input, isGPS, isGLO, isGAL, isBDS, k, settings,
    Epoch.corr2brdc_clk(:,prn));

Error in calc_float_solution (line 54)
        [model, Epoch] = modelErrorSources(settings, input, Epoch, model, Adjust, obs);

Error in ZD_processing (line 47)
    calc_float_solution(input, obs, Adjust, Epoch, settings);

Error in PPP_main (line 324)
        ZD_processing(HMW_12, HMW_23, HMW_13, Adjust, Epoch, settings, input, satellites, obs);

Error in StartProcessingFromGUI (line 164)
    settings_ = PPP_main(settings);         % start processing

Error in GUI_PPP>pushbutton_run_Callback (line 4168)
handles = StartProcessingFromGUI(handles);      % starts PPP_main.n

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in GUI_PPP (line 28)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)GUI_PPP('pushbutton_run_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by mfglaner** [comment]
The satellite clock does not contain the necessary data. 
Please send the RINEX File and the settings from the GUI (settings.mat) to [rapppid@geo.tuwien.ac.at].
