### ISSUE TITLE
read_erp fails to read IGS rapid ERP files

### ISSUE THREAD

**Issue by Jorgeminator** [TUW-VieVS/raPPPid#20]
The formatting of the Rapid ERP files from IGS differ slightly from the final product. Due to this difference, read_erp fails when attempting to read those files.

**Comment by mfglaner** [comment]
Thank you for this comment. I have not tested the IGS rapid products during the implementation. I will correct this. Anyway, I think the effect of the Polar Tides is not critical when using rapid satellite products because this correction is rather small.

**Comment by mfglaner** [comment]
Please add 
isempty(line) 
to the if condition in line 30. I will push an updated version of the whole function soon.

**Comment by mfglaner** [comment]
Closr
