### ISSUE TITLE
 'PARAMETERS'  can't be found

### ISSUE THREAD

**Issue by hshsjjjeueu** [TUW-VieVS/raPPPid#3]
错误使用 save
由于 'PARAMETERS' 不存在，无法创建 'default.mat'。

出错 GUI_PPP>GUI_PPP_OpeningFcn (第 102 行)
save(defaultParamFilename, 'parameters')    % save variable settings into file

出错 gui_mainfcn (第 220 行)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

出错 GUI_PPP (第 28 行)
    gui_mainfcn(gui_State, varargin{:});

**Comment by mfglaner** [comment]
In this line, the default parameters of the GUI are saved to WORK/PARAMETERS/default.mat. My guess is that you have changed the folder structure of raPPPid and the folder WORK/PARAMETERS/ does not exist. Please keep the folder structure of raPPPid to avoid errors. Alternatively, you can try to comment out this line. 
I will include a validation if the folder exists in the next release.

**Comment by hshsjjjeueu** [comment]
Thank you for your advice whicle had solved my question.But I have another question。 When I come out of results, I found that the accuracy of&nbsp; the float is higher than the accuracy of the fixed,which is unresonable。Will it is realvant to the bias? Because settings_summary.txt&nbsp; doesn't occurs Phase bias.
I will appreciate it very match if you give me a reply as soon as possible.







Min
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TUW-VieVS/raPPPid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月31日(星期一) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TUW-VieVS/raPPPid]  'PARAMETERS'  can't be found (Issue #3)





 
Closed #3 as completed.

**Comment by mfglaner** [comment]
You can not fix phase ambiguities in PPP without suitable phase biases. Please consider using a parameter file provided within the raPPPid package or check the raPPPid wiki for processing examples.
