### ISSUE TITLE
GUI start error 

### ISSUE THREAD

**Issue by howiie11** [TUW-VieVS/raPPPid#4]
I use MATLAB 2018a and change folder to /WORK folder, but an error occur when I start the raPPPid.m
it shows :  please check the current folder and path.m

**Comment by mfglaner** [comment]
raPPPid checks if the CODE, DATA, and RESULTS folders are existing before opening the GUI. If one is missing, the mentioned error is shown. Please make sure that these folder are existing (e.g., do not manipulate the folder structure).
