### ISSUE TITLE
MATLAB R2018a problem

### ISSUE THREAD

**Issue by howiie11** [TUW-VieVS/raPPPid#7]
Which MATLAB version should I use?

I used MATLAB R2018a but it always shows following problem:

wrong use append (line 38)
Wrong number of input arguments for obsolete matrix-based syntax.
  error at ElevationWeightingFunction (line 23)
funstring = append('@(e)', funstring);
  error at getSettingsFromGUI (line 349)
ElevationWeightingFunction(get(handles.edit_elevation_weighting_function, 'String'));
  error at GUI_PPP>GUI_PPP_OpeningFcn (line 100)
settings = getSettingsFromGUI(handles); % get input from GUI and put it into structure "settings" 
 error at gui_mainfcn (line 220)
 
feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});
error at GUI_PPP (line 28)
  gui_mainfcn(gui_State, varargin{:});

 error at raPPPid (line 15)
    GUI_PPP();

**Comment by mfglaner** [comment]
The function append() was introduced in R2019a and raPPPid should work with this Matlab version or higher.
However, I will replace append() to ensure compatibility with older Matlab versions.

**Comment by mfglaner** [comment]
1) ElevationWeightingFunction.m
replace `funstring = append('@(e)', funstring);` with `funstring = ['@(e)' funstring];`

2) SNRWeightingFunction.m
replace `funstring = append('@(snr)', funstring);` with `funstring = ['@(snr)' funstring];`
replace `funstring = append('@(SNR)', funstring);` with `funstring = ['@(SNR)' funstring];`

I will include these changes in the next release of raPPPid.
