### ISSUE TITLE
the uncombined PPP model

### ISSUE THREAD

**Issue by millpoint** [TUW-VieVS/raPPPid#9]
Hi, I am a little confused about the uncombined PPP model in your paper, the term DCB1i is presented in equations (7) and (8). In my understanding, the receiver DCB is not involved in phase observable.  Could you please provide some clarification on this term?

**Comment by mfglaner** [comment]
In the current implementation of the uncombined model, raPPPid uses code and phase to estimate the receiver DCBs. Therefore, the receiver DCBs are included in the code and phase observation equation. 
Using only the code observations for estimating the receiver DCBs should also be fine. I guess these different approaches result in a shift of the float ambiguities. Therefore, it does not matter for float PPP, but I need to check this when performing PPP-AR with the uncombined model.

**Comment by mfglaner** [comment]
In the current implementation of the uncombined model, raPPPid uses code and phase to estimate the receiver DCBs. Therefore, the receiver DCBs are included in the code and phase observation equation.
Using only the code observations for estimating the receiver DCBs should also be fine. I guess these different approaches result in a shift of the float ambiguities. Therefore, it does not matter for float PPP, but I need to check this when performing PPP-AR with the uncombined model.
